#!/usr/bin/env bash
# Install Python deps, detect qbittorrent-nox, create .env with secrets if missing, start PM2 on port 8000.
# Optional env knobs (zip SQLite, health deep checks, IP allowlist, signed file URLs, audit, webhooks,
# RSS, qBittorrent throughput QBITTORRENT_MAX_* / *_ACTIVE_* / *_ASYNC_IO_*): see .env.example and DEPLOYMENT.md. Docker: docker-compose.yml + Dockerfile.
#
# Web UI (after deploy): / — overview (disk, magnets, HTTP preview)
#                        /torrents — BT transfers + charts (Chart.js CDN)
#                        /files — browse & delete
#                        /activity — live HTTP /files/… connections (IP, UA, Range)
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

info() { printf '[build] %s\n' "$*"; }
die() { printf '[build] ERROR: %s\n' "$*" >&2; exit 1; }

# Append KEY=val to .env if that key is not already set (first line wins).
_append_env_if_missing() {
  local envf="$1" key="$2" val="$3"
  if ! grep -q "^${key}=" "$envf"; then
    echo "${key}=${val}" >> "$envf"
    info "appended ${key}=${val}"
  fi
}

PYTHON_BIN="${PYTHON_BIN:-python3}"
if ! command -v "$PYTHON_BIN" >/dev/null 2>&1; then
  die "python3 not found. Install Python 3.10+ or set PYTHON_BIN."
fi

if ! command -v openssl >/dev/null 2>&1; then
  die "openssl not found (needed to generate secrets)."
fi

# --- qBittorrent-nox (BitTorrent engine) -----------------------------------
# Prefer system package; on Linux without root, fetch a static binary from
# https://github.com/userdocs/qbittorrent-nox-static (releases/latest).
# Set QBITTORRENT_SKIP_STATIC_INSTALL=1 to disable that fetch.

download_to_file() {
  local url="$1" out="$2"
  if command -v curl >/dev/null 2>&1; then
    curl -fL --connect-timeout 20 --max-time 600 -o "$out" "$url"
  elif command -v wget >/dev/null 2>&1; then
    wget -qO "$out" "$url"
  else
    return 1
  fi
}

qbt_static_asset_name() {
  case "$(uname -m)" in
    x86_64 | amd64) echo "x86_64-qbittorrent-nox" ;;
    aarch64 | arm64) echo "aarch64-qbittorrent-nox" ;;
    armv7l) echo "armv7-qbittorrent-nox" ;;
    armv6l | armhf) echo "armhf-qbittorrent-nox" ;;
    riscv64) echo "riscv64-qbittorrent-nox" ;;
    i386 | i686) echo "x86-qbittorrent-nox" ;;
    *) echo "" ;;
  esac
}

install_qbittorrent_nox_static() {
  local asset dest tmp url
  [[ "$(uname -s)" == "Linux" ]] || return 1
  [[ "${QBITTORRENT_SKIP_STATIC_INSTALL:-0}" != "1" ]] || return 1
  asset="$(qbt_static_asset_name)"
  [[ -n "$asset" ]] || return 1
  dest="${HOME}/.local/bin/qbittorrent-nox"
  mkdir -p "${HOME}/.local/bin"
  tmp="$(mktemp)"
  url="https://github.com/userdocs/qbittorrent-nox-static/releases/latest/download/${asset}"
  info "Downloading static qbittorrent-nox (${asset}) to ${dest} …"
  if ! download_to_file "$url" "$tmp"; then
    rm -f "$tmp"
    return 1
  fi
  chmod +x "$tmp"
  mv -f "$tmp" "$dest"
  export PATH="${HOME}/.local/bin:${PATH}"
  info "Installed static qbittorrent-nox (userdocs/qbittorrent-nox-static)."
  return 0
}

QBT_BIN=""
if [[ -n "${QBITTORRENT_BIN:-}" ]]; then
  QBT_BIN="${QBITTORRENT_BIN}"
elif [[ -n "${QBITTORRENT_BIN_OVERRIDE:-}" ]]; then
  QBT_BIN="${QBITTORRENT_BIN_OVERRIDE}"
elif command -v qbittorrent-nox >/dev/null 2>&1; then
  QBT_BIN="$(command -v qbittorrent-nox)"
elif [[ -x "${HOME}/.local/bin/qbittorrent-nox" ]]; then
  QBT_BIN="${HOME}/.local/bin/qbittorrent-nox"
elif [[ -x /usr/bin/qbittorrent-nox ]]; then
  QBT_BIN="/usr/bin/qbittorrent-nox"
elif [[ -x /usr/local/bin/qbittorrent-nox ]]; then
  QBT_BIN="/usr/local/bin/qbittorrent-nox"
elif install_qbittorrent_nox_static; then
  QBT_BIN="${HOME}/.local/bin/qbittorrent-nox"
fi

if [[ -z "$QBT_BIN" || ! -x "$QBT_BIN" ]]; then
  die "qbittorrent-nox not found. Install it (e.g. apt install qbittorrent-nox, brew install qbittorrent), set QBITTORRENT_BIN, or on Linux leave QBITTORRENT_SKIP_STATIC_INSTALL unset and use curl/wget to fetch a static build."
fi
info "Using qBittorrent at: $QBT_BIN"

# --- venv + Python dependencies -------------------------------------------
info "Creating venv with $PYTHON_BIN …"
"$PYTHON_BIN" -m venv "$ROOT/.venv"
"$ROOT/.venv/bin/pip" install --upgrade pip wheel
"$ROOT/.venv/bin/pip" install -r "$ROOT/requirements.txt"

# --- .env with secrets -----------------------------------------------------
ENV_FILE="$ROOT/.env"
NEW_ENV=0
if [[ ! -f "$ENV_FILE" ]]; then
  NEW_ENV=1
  SECRET_KEY="$(openssl rand -hex 48)"
  DASHBOARD_PASSWORD="$(openssl rand -hex 24)"

  cat > "$ENV_FILE" <<EOF
# Generated by build.sh — keep private (chmod 600).
# Full reference: .env.example (copy optional lines below as needed).

SECRET_KEY=${SECRET_KEY}
DASHBOARD_PASSWORD=${DASHBOARD_PASSWORD}
DOWNLOAD_DIR=${HOME}/torrents
HOST=0.0.0.0
PORT=8000
FLASK_DEBUG=0
SESSION_COOKIE_SECURE=0
SESSION_HOURS=10

# --- qBittorrent (managed by the app when QBITTORRENT_URL is unset) ----------
QBITTORRENT_AUTO_START=1
QBITTORRENT_STATE_DIR=${HOME}/.cache/torrent-server
QBITTORRENT_BYPASS_LOCAL_AUTH=1
QBITTORRENT_BIN=${QBT_BIN}
# Optional fixed WebUI port for auto-spawned daemon (otherwise an ephemeral localhost port is chosen).
# QBITTORRENT_WEBUI_PORT=8080

# --- qBittorrent throughput defaults (fed into app setPreferences on login; tune ulimit -n / sysctl for 10G) ---
QBITTORRENT_MAX_CONNEC=5000
QBITTORRENT_MAX_CONNEC_PER_TORRENT=800
QBITTORRENT_MAX_UPLOAD_SLOTS=-1
QBITTORRENT_MAX_UPLOAD_SLOTS_PER_TORRENT=-1
QBITTORRENT_MAX_ACTIVE_DOWNLOADS=50
QBITTORRENT_MAX_ACTIVE_TORRENTS=200
QBITTORRENT_MAX_ACTIVE_UPLOADS=100
QBITTORRENT_MAX_ACTIVE_CHECKING=32
QBITTORRENT_QUEUEING_ENABLED=1
QBITTORRENT_DONT_COUNT_SLOW_TORRENTS=1
QBITTORRENT_SLOW_TORRENT_DL_KIB=50
QBITTORRENT_UTP_TCP_MIXED_MODE=0
QBITTORRENT_ASYNC_IO_THREADS=8
QBITTORRENT_FILE_POOL_SIZE=500
# Optional: force TCP (if uTP is slow): QBITTORRENT_BT_PROTOCOL=tcp
# Optional explicit B/s caps for setPreferences: QBITTORRENT_MAX_DOWNLOAD_BPS=0 QBITTORRENT_MAX_UPLOAD_BPS=0

# Per-torrent rate limits use the same env names as the old aria2 build for compatibility (0 = unlimited):
ARIA2_MAX_UPLOAD_LIMIT=0
ARIA2_MAX_DOWNLOAD_LIMIT=0
ARIA2_SEED_TIME=0
ARIA2_SEED_RATIO=0
RATELIMIT_STORAGE_URI=memory://

# --- Optional (defaults shown; uncomment to enable / override) ---
# HEALTH_DEEP=0
# LOG_JSON=0
# LOG_LEVEL=INFO
# TRUST_X_FORWARDED_FOR=0
# DASHBOARD_ALLOWED_CIDRS=
# ZIP_STORAGE_DIR=
# ZIP_JOB_DB=
# ZIP_MAX_CONCURRENT=2
# ZIP_MAX_AGE_DAYS=0
# ZIP_MAX_TOTAL_BYTES=0
# FILES_DOWNLOAD_TOKEN_SECRET=
# FILES_DOWNLOAD_TOKEN_MAX_AGE=604800
# AUDIT_LOG_PATH=
# NOTIFY_WEBHOOK_URL=
# ENABLE_RSS_GRABS=0
# RSS_FEED_URL=
# RSS_POLL_SECONDS=900
# RSS_MAX_MAGNETS_PER_POLL=5
# RSS_PARENT_SUBDIR=
# RSS_STATE_DB=
EOF
  chmod 600 "$ENV_FILE"
  info "Created $ENV_FILE"
else
  info "keeping existing $ENV_FILE"
  if ! grep -q '^QBITTORRENT_STATE_DIR=' "$ENV_FILE"; then
    echo "QBITTORRENT_STATE_DIR=${HOME}/.cache/torrent-server" >> "$ENV_FILE"
    info "appended QBITTORRENT_STATE_DIR"
  fi
  if ! grep -q '^QBITTORRENT_BIN=' "$ENV_FILE" && [[ "$QBT_BIN" == "${HOME}/.local/bin/qbittorrent-nox" ]]; then
    echo "QBITTORRENT_BIN=${QBT_BIN}" >> "$ENV_FILE"
    info "appended QBITTORRENT_BIN (static install path)"
  fi
  if ! grep -q '^QBITTORRENT_AUTO_START=' "$ENV_FILE"; then
    echo "QBITTORRENT_AUTO_START=1" >> "$ENV_FILE"
    info "appended QBITTORRENT_AUTO_START"
  fi
  if ! grep -q '^PORT=' "$ENV_FILE"; then
    echo "PORT=8000" >> "$ENV_FILE"
    info "appended PORT=8000"
  fi
  if ! grep -q '^HOST=' "$ENV_FILE"; then
    echo "HOST=0.0.0.0" >> "$ENV_FILE"
    info "appended HOST=0.0.0.0"
  fi
  if ! grep -q '^FLASK_DEBUG=' "$ENV_FILE"; then
    echo "FLASK_DEBUG=0" >> "$ENV_FILE"
  fi
  if ! grep -q '^ARIA2_SEED_RATIO=' "$ENV_FILE"; then
    echo "ARIA2_SEED_RATIO=0" >> "$ENV_FILE"
    info "appended ARIA2_SEED_RATIO=0"
  fi
  # --- High-throughput + rate-limit defaults (match qbittorrent_service throughput_preferences_from_env) ---
  _append_env_if_missing "$ENV_FILE" ARIA2_MAX_UPLOAD_LIMIT 0
  _append_env_if_missing "$ENV_FILE" ARIA2_MAX_DOWNLOAD_LIMIT 0
  _append_env_if_missing "$ENV_FILE" QBITTORRENT_BYPASS_LOCAL_AUTH 1
  _append_env_if_missing "$ENV_FILE" QBITTORRENT_MAX_CONNEC 5000
  _append_env_if_missing "$ENV_FILE" QBITTORRENT_MAX_CONNEC_PER_TORRENT 800
  _append_env_if_missing "$ENV_FILE" QBITTORRENT_MAX_UPLOAD_SLOTS -1
  _append_env_if_missing "$ENV_FILE" QBITTORRENT_MAX_UPLOAD_SLOTS_PER_TORRENT -1
  _append_env_if_missing "$ENV_FILE" QBITTORRENT_MAX_ACTIVE_DOWNLOADS 50
  _append_env_if_missing "$ENV_FILE" QBITTORRENT_MAX_ACTIVE_TORRENTS 200
  _append_env_if_missing "$ENV_FILE" QBITTORRENT_MAX_ACTIVE_UPLOADS 100
  _append_env_if_missing "$ENV_FILE" QBITTORRENT_MAX_ACTIVE_CHECKING 32
  _append_env_if_missing "$ENV_FILE" QBITTORRENT_QUEUEING_ENABLED 1
  _append_env_if_missing "$ENV_FILE" QBITTORRENT_DONT_COUNT_SLOW_TORRENTS 1
  _append_env_if_missing "$ENV_FILE" QBITTORRENT_SLOW_TORRENT_DL_KIB 50
  _append_env_if_missing "$ENV_FILE" QBITTORRENT_UTP_TCP_MIXED_MODE 0
  _append_env_if_missing "$ENV_FILE" QBITTORRENT_ASYNC_IO_THREADS 8
  _append_env_if_missing "$ENV_FILE" QBITTORRENT_FILE_POOL_SIZE 500
  if ! grep -q '^# --- torrent-server optional vars' "$ENV_FILE"; then
    cat >> "$ENV_FILE" <<'OPTIONAL_EOF'

# --- torrent-server optional vars (see .env.example for descriptions) ---
# HEALTH_DEEP=0
# LOG_JSON=0
# LOG_LEVEL=INFO
# TRUST_X_FORWARDED_FOR=0
# DASHBOARD_ALLOWED_CIDRS=
# ZIP_STORAGE_DIR=
# ZIP_JOB_DB=
# ZIP_MAX_CONCURRENT=2
# ZIP_MAX_AGE_DAYS=0
# ZIP_MAX_TOTAL_BYTES=0
# FILES_DOWNLOAD_TOKEN_SECRET=
# FILES_DOWNLOAD_TOKEN_MAX_AGE=604800
# AUDIT_LOG_PATH=
# NOTIFY_WEBHOOK_URL=
# ENABLE_RSS_GRABS=0
# RSS_FEED_URL=
# RSS_POLL_SECONDS=900
# RSS_MAX_MAGNETS_PER_POLL=5
# RSS_PARENT_SUBDIR=
# RSS_STATE_DB=
# (Throughput defaults are appended by build.sh; see .env.example for QBITTORRENT_SKIP_THROUGHPUT_PREFS, BT_PROTOCOL, sockets, seeding.)
OPTIONAL_EOF
    info "appended optional-var comments (see .env.example)"
  fi
fi

chmod +x "$ROOT/run.sh"

if [[ "$NEW_ENV" -eq 1 ]]; then
  PASS_SHOW=""
  PASS_SHOW="$(grep '^DASHBOARD_PASSWORD=' "$ENV_FILE" | cut -d= -f2- || true)"
  echo ""
  echo "================================================================"
  echo "  Dashboard password (save this — shown once):"
  echo "  ${PASS_SHOW}"
  echo "================================================================"
  echo ""
fi

# --- OS-level network/fd tuning reminder ----------------------------------
info "NOTE: For sustained 10G throughput, ensure these sysctl values are set:"
info "  net.core.rmem_max=536870912"
info "  net.core.wmem_max=536870912"
info "  net.ipv4.tcp_rmem='4096 87380 536870912'"
info "  net.ipv4.tcp_wmem='4096 65536 536870912'"
info "  net.core.netdev_max_backlog=30000"
info "  and ulimit -n 1048576 for the process user."
info "  Add to /etc/sysctl.conf + run: sudo sysctl -p"

# --- PM2 ------------------------------------------------------------------
if ! command -v pm2 >/dev/null 2>&1; then
  die "pm2 not found. Install Node.js then: npm install -g pm2"
fi

pm2 delete weedr >/dev/null 2>&1 || true
pm2 start "$ROOT/run.sh" --name weedr --time --interpreter bash
pm2 save

LISTEN_HOST="$(grep -E '^HOST=' "$ENV_FILE" | tail -n1 | cut -d= -f2- || echo 0.0.0.0)"
LISTEN_PORT="$(grep -E '^PORT=' "$ENV_FILE" | tail -n1 | cut -d= -f2- || echo 8000)"
info "PM2 app 'weedr' started — http://${LISTEN_HOST}:${LISTEN_PORT}"
info "Logs: pm2 logs weedr   Restart: pm2 restart weedr"
if ! pm2 startup >/dev/null 2>&1; then
  info "Optional: run \`pm2 startup\` (as root) so the app restarts after reboot."
fi
