#!/usr/bin/env bash
# Install Python deps, detect aria2, create .env with secrets if missing, start PM2 on port 8000.
# Optional env knobs (zip SQLite, health deep checks, IP allowlist, signed file URLs, audit, webhooks,
# RSS): see .env.example and DEPLOYMENT.md. Docker: docker-compose.yml + Dockerfile.
#
# Web UI (after deploy): / — overview (disk, magnets, HTTP preview)
#                        /torrents — BT transfers + charts (Chart.js CDN)
#                        /files — browse & delete
#                        /activity — live HTTP /files/… connections (IP, UA, Range)
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

info() { printf '[build] %s\n' "$*"; }
die() { printf '[build] ERROR: %s\n' "$*" >&2; exit 1; }

PYTHON_BIN="${PYTHON_BIN:-python3}"
if ! command -v "$PYTHON_BIN" >/dev/null 2>&1; then
  die "python3 not found. Install Python 3.10+ or set PYTHON_BIN."
fi

if ! command -v openssl >/dev/null 2>&1; then
  die "openssl not found (needed to generate secrets)."
fi

# --- aria2: resolve binary path for ARIA2_BIN ------------------------------
ARIA2_BIN=""
if [[ -n "${ARIA2_BIN_OVERRIDE:-}" ]]; then
  ARIA2_BIN="$ARIA2_BIN_OVERRIDE"
elif command -v aria2c >/dev/null 2>&1; then
  ARIA2_BIN="$(command -v aria2c)"
elif [[ -x /usr/local/bin/aria2c ]]; then
  ARIA2_BIN="/usr/local/bin/aria2c"
elif [[ -x /usr/bin/aria2c ]]; then
  ARIA2_BIN="/usr/bin/aria2c"
elif [[ -x "$HOME/.local/bin/aria2c" ]]; then
  ARIA2_BIN="$HOME/.local/bin/aria2c"
fi

if [[ -z "$ARIA2_BIN" || ! -x "$ARIA2_BIN" ]]; then
  die "aria2c not found. Install aria2 (e.g. sudo apt-get install -y aria2) or set ARIA2_BIN_OVERRIDE."
fi
info "Using aria2 at: $ARIA2_BIN"

# --- venv + Python dependencies -------------------------------------------
info "Creating venv with $PYTHON_BIN …"
"$PYTHON_BIN" -m venv "$ROOT/.venv"
"$ROOT/.venv/bin/pip" install --upgrade pip wheel
"$ROOT/.venv/bin/pip" install -r "$ROOT/requirements.txt"

# --- .env with secrets -----------------------------------------------------
ENV_FILE="$ROOT/.env"
NEW_ENV=0
if [[ ! -f "$ENV_FILE" ]]; then
  NEW_ENV=1
  SECRET_KEY="$(openssl rand -hex 48)"
  DASHBOARD_PASSWORD="$(openssl rand -hex 24)"

  cat > "$ENV_FILE" <<EOF
# Generated by build.sh — keep private (chmod 600).
# Full reference: .env.example (copy optional lines below as needed).

SECRET_KEY=${SECRET_KEY}
DASHBOARD_PASSWORD=${DASHBOARD_PASSWORD}
ARIA2_BIN=${ARIA2_BIN}
DOWNLOAD_DIR=${HOME}/torrents
HOST=0.0.0.0
PORT=8000
FLASK_DEBUG=0
SESSION_COOKIE_SECURE=0
SESSION_HOURS=10
ARIA2_MAX_CONCURRENT=5
ARIA2_MAX_CONNECTION_PER_SERVER=16
ARIA2_SPLIT=64
ARIA2_MIN_SPLIT_SIZE=10M
ARIA2_BT_MAX_PEERS=100
ARIA2_DISK_CACHE=128M
ARIA2_FILE_ALLOCATION=none
ARIA2_BT_ENABLE_LPD=1
ARIA2_DHT_LISTEN_PORT=6881-6999
ARIA2_BT_FORCE_ENCRYPTION=1
ARIA2_MAX_UPLOAD_LIMIT=0
ARIA2_MAX_DOWNLOAD_LIMIT=0
ARIA2_SEED_TIME=0
ARIA2_SEED_RATIO=0
RATELIMIT_STORAGE_URI=memory://

# --- Optional (defaults shown; uncomment to enable / override) ---
# HEALTH_DEEP=0
# LOG_JSON=0
# LOG_LEVEL=INFO
# TRUST_X_FORWARDED_FOR=0
# DASHBOARD_ALLOWED_CIDRS=
# ZIP_STORAGE_DIR=
# ZIP_JOB_DB=
# ZIP_MAX_CONCURRENT=2
# ZIP_MAX_AGE_DAYS=0
# ZIP_MAX_TOTAL_BYTES=0
# FILES_DOWNLOAD_TOKEN_SECRET=
# FILES_DOWNLOAD_TOKEN_MAX_AGE=604800
# AUDIT_LOG_PATH=
# NOTIFY_WEBHOOK_URL=
# ENABLE_RSS_GRABS=0
# RSS_FEED_URL=
# RSS_POLL_SECONDS=900
# RSS_MAX_MAGNETS_PER_POLL=5
# RSS_PARENT_SUBDIR=
# RSS_STATE_DB=
EOF
  chmod 600 "$ENV_FILE"
  info "Created $ENV_FILE"
else
  info "keeping existing $ENV_FILE"
  if ! grep -q '^ARIA2_BIN=' "$ENV_FILE"; then
    printf '\nARIA2_BIN=%s\n' "$ARIA2_BIN" >> "$ENV_FILE"
    info "appended ARIA2_BIN"
  fi
  if ! grep -q '^PORT=' "$ENV_FILE"; then
    echo "PORT=8000" >> "$ENV_FILE"
    info "appended PORT=8000"
  fi
  if ! grep -q '^HOST=' "$ENV_FILE"; then
    echo "HOST=0.0.0.0" >> "$ENV_FILE"
    info "appended HOST=0.0.0.0"
  fi
  if ! grep -q '^FLASK_DEBUG=' "$ENV_FILE"; then
    echo "FLASK_DEBUG=0" >> "$ENV_FILE"
  fi
  if ! grep -q '^ARIA2_SEED_RATIO=' "$ENV_FILE"; then
    echo "ARIA2_SEED_RATIO=0" >> "$ENV_FILE"
    info "appended ARIA2_SEED_RATIO=0"
  fi
  if ! grep -q '^# --- torrent-server optional vars' "$ENV_FILE"; then
    cat >> "$ENV_FILE" <<'OPTIONAL_EOF'

# --- torrent-server optional vars (see .env.example for descriptions) ---
# HEALTH_DEEP=0
# LOG_JSON=0
# LOG_LEVEL=INFO
# TRUST_X_FORWARDED_FOR=0
# DASHBOARD_ALLOWED_CIDRS=
# ZIP_STORAGE_DIR=
# ZIP_JOB_DB=
# ZIP_MAX_CONCURRENT=2
# ZIP_MAX_AGE_DAYS=0
# ZIP_MAX_TOTAL_BYTES=0
# FILES_DOWNLOAD_TOKEN_SECRET=
# FILES_DOWNLOAD_TOKEN_MAX_AGE=604800
# AUDIT_LOG_PATH=
# NOTIFY_WEBHOOK_URL=
# ENABLE_RSS_GRABS=0
# RSS_FEED_URL=
# RSS_POLL_SECONDS=900
# RSS_MAX_MAGNETS_PER_POLL=5
# RSS_PARENT_SUBDIR=
# RSS_STATE_DB=
# (aria2 tuning defaults are in .env.example — ARIA2_MAX_CONCURRENT, ARIA2_DHT_LISTEN_PORT, …)
OPTIONAL_EOF
    info "appended optional-var comments (see .env.example)"
  fi
fi

chmod +x "$ROOT/run.sh"

if [[ "$NEW_ENV" -eq 1 ]]; then
  PASS_SHOW=""
  PASS_SHOW="$(grep '^DASHBOARD_PASSWORD=' "$ENV_FILE" | cut -d= -f2- || true)"
  echo ""
  echo "================================================================"
  echo "  Dashboard password (save this — shown once):"
  echo "  ${PASS_SHOW}"
  echo "================================================================"
  echo ""
fi

# --- PM2 ------------------------------------------------------------------
if ! command -v pm2 >/dev/null 2>&1; then
  die "pm2 not found. Install Node.js then: npm install -g pm2"
fi

pm2 delete torrent-server >/dev/null 2>&1 || true
pm2 start "$ROOT/run.sh" --name torrent-server --time --interpreter bash
pm2 save

LISTEN_HOST="$(grep -E '^HOST=' "$ENV_FILE" | tail -n1 | cut -d= -f2- || echo 0.0.0.0)"
LISTEN_PORT="$(grep -E '^PORT=' "$ENV_FILE" | tail -n1 | cut -d= -f2- || echo 8000)"
info "PM2 app 'torrent-server' started — http://${LISTEN_HOST}:${LISTEN_PORT}"
info "Logs: pm2 logs torrent-server   Restart: pm2 restart torrent-server"
if ! pm2 startup >/dev/null 2>&1; then
  info "Optional: run \`pm2 startup\` (as root) so the app restarts after reboot."
fi
